-- ==============================================================================
-- REVORA ATHLETE RECOVERY — SUPABASE PROFILES TABLE SETUP & PERMISSIONS
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 1. Create or ensure profiles table exists with proper types & constraints
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  date_of_birth TEXT,
  gender TEXT,
  primary_sport TEXT,
  custom_sport TEXT,
  activity_level TEXT,
  training_frequency TEXT,
  has_previous_injuries BOOLEAN DEFAULT false,
  injury_history_details TEXT,
  current_training_details TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Grant table-level access to Supabase client roles (fixes error 42501)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.profiles TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 4. Clean up any previous policies to prevent duplicates
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can manage own profile" ON public.profiles;

-- 5. Create RLS Policies allowing authenticated users full access to their own profile
CREATE POLICY "Users can view their own profile"
  ON public.profiles
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile"
  ON public.profiles
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
  ON public.profiles
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ==============================================================================
-- 6. ASSESSMENTS TABLE (PHASE 5 — INJURY ASSESSMENT)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  activity TEXT NOT NULL,
  custom_activity TEXT,
  activity_context TEXT,
  onset_type TEXT,
  body_areas TEXT[] NOT NULL,
  pain_severity INTEGER NOT NULL CHECK (pain_severity >= 0 AND pain_severity <= 10),
  symptoms TEXT[] NOT NULL,
  custom_symptom TEXT,
  duration TEXT NOT NULL,
  movement_limitation TEXT,
  additional_details TEXT,
  status TEXT DEFAULT 'completed',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Grant table-level access for assessments table
GRANT ALL ON TABLE public.assessments TO anon, authenticated, service_role;

-- Enable Row Level Security on assessments table
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;

-- Clean up any previous assessments policies
DROP POLICY IF EXISTS "Users can view their own assessments" ON public.assessments;
DROP POLICY IF EXISTS "Users can insert their own assessments" ON public.assessments;
DROP POLICY IF EXISTS "Users can update their own assessments" ON public.assessments;

-- Create RLS Policies for authenticated users on assessments table
CREATE POLICY "Users can view their own assessments"
  ON public.assessments
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own assessments"
  ON public.assessments
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own assessments"
  ON public.assessments
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ==============================================================================
-- 7. RECOVERY CHECK-INS TABLE & POLICIES
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.recovery_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  sleep_hours DOUBLE PRECISION NOT NULL,
  resting_heart_rate INTEGER NOT NULL,
  hrv_ms DOUBLE PRECISION,
  soreness INTEGER NOT NULL CHECK (soreness >= 1 AND soreness <= 10),
  energy_level INTEGER NOT NULL CHECK (energy_level >= 1 AND energy_level <= 10),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_recovery_checkins_user_id ON public.recovery_checkins(user_id);
CREATE INDEX IF NOT EXISTS idx_recovery_checkins_created_at ON public.recovery_checkins(created_at DESC);

-- Table permissions
GRANT ALL ON TABLE public.recovery_checkins TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Enable Row Level Security
ALTER TABLE public.recovery_checkins ENABLE ROW LEVEL SECURITY;

-- Clean up any previous policies to prevent duplicates
DROP POLICY IF EXISTS "Users can view their own recovery checkins" ON public.recovery_checkins;
DROP POLICY IF EXISTS "Users can insert their own recovery checkins" ON public.recovery_checkins;
DROP POLICY IF EXISTS "Users can update their own recovery checkins" ON public.recovery_checkins;
DROP POLICY IF EXISTS "Users can delete their own recovery checkins" ON public.recovery_checkins;

-- Create RLS Policies for authenticated users
CREATE POLICY "Users can view their own recovery checkins"
  ON public.recovery_checkins
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own recovery checkins"
  ON public.recovery_checkins
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own recovery checkins"
  ON public.recovery_checkins
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own recovery checkins"
  ON public.recovery_checkins
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);
