import React from "react";
import { AlertCircle, ShieldAlert } from "lucide-react";

interface RecoverySafetyCardProps {
  customGuidelines?: string[];
}

export const RecoverySafetyCard: React.FC<RecoverySafetyCardProps> = ({
  customGuidelines,
}) => {
  const hasCustom = customGuidelines && customGuidelines.length > 0;

  return (
    <div className="p-5 sm:p-6 rounded-2xl bg-[#18132D] border border-[#7C3AED]/25 space-y-3 shadow-lg">
      <div className="flex items-center justify-between pb-2 border-b border-[#7C3AED]/15">
        <div className="flex items-center gap-2">
          <ShieldAlert className="w-4 h-4 text-[#FDBA8C]" />
          <h3 className="text-xs font-bold uppercase tracking-wider text-[#FDBA8C] font-display">
            Safety & Movement Guidance
          </h3>
        </div>
        <span className="text-[11px] text-[#B8AEC8]">Athlete Guidelines</span>
      </div>

      {hasCustom ? (
        <ul className="space-y-2 text-xs text-[#E9E2F5]">
          {customGuidelines.map((g, idx) => (
            <li key={idx} className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-[#F97368] shrink-0 mt-1.5" />
              <span>{g}</span>
            </li>
          ))}
        </ul>
      ) : (
        <div className="space-y-2">
          <p className="text-xs text-[#B8AEC8] leading-relaxed">
            Safety guidance and movement precautions will appear here once your personalized recovery plan is generated by the REVORA engine.
          </p>
          <div className="p-3 rounded-xl bg-[#120D26]/70 border border-[#7C3AED]/15 flex items-start gap-2 text-[11px] text-[#B8AEC8]">
            <AlertCircle className="w-3.5 h-3.5 text-[#FDBA8C] shrink-0 mt-0.5" />
            <span>
              Always discontinue any movement that produces sharp or worsening discomfort. Consult a sports medicine clinician for clinical rehabilitation.
            </span>
          </div>
        </div>
      )}
    </div>
  );
};
